package com.kvbadev.wms;

import com.kvbadev.wms.data.ItemRepository;
import com.kvbadev.wms.models.Item;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import java.util.Objects;

@ExtendWith(SpringExtension.class)
@DataJpaTest
public class ItemRepositoryTests {
    @Autowired
    private ItemRepository itemRepository;

    Item testItem = new Item("Test1", "test2", 4450);

    @Test
    public void saveAndExamineItem() {
        itemRepository.save(testItem);
        var res = itemRepository.findAll();
        var item = res.get(0);

        assert item != null;
        assert item.getId() == 1;
        assert Objects.equals(item.getNormalizedNetPrice(), testItem.getNormalizedNetPrice());
    }

    @Test
    public void removeItem() {
        itemRepository.save(testItem);
        //Id == 2 because the number is autogenerated by the database and in previous test, there was one object added
        var product = itemRepository.findById(2).orElseThrow();

        itemRepository.delete(product);
        assert itemRepository.findById(2).isEmpty();
    }
}
